/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculos.jPanels;
import java.text.DecimalFormat;

/**
 *
 * @author Tiago
 */
public class Equacao2Grau extends javax.swing.JPanel {

    /**
     * Creates new form Equacao2Grau
     */
    public Equacao2Grau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        lblX1 = new javax.swing.JLabel();
        lblX2 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        btnEquac = new javax.swing.JButton();
        btnZerarEq = new javax.swing.JButton();
        lblDeltaMenor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPasso1 = new javax.swing.JLabel();
        lblPasso2 = new javax.swing.JLabel();
        lblPasso4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblA.setText("a");

        lblB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblB.setText("b");

        lblC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblC.setText("c");

        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtC.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblX1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX1.setText("X'");

        lblX2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX2.setText("X''");

        txtX1.setEditable(false);
        txtX1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtX2.setEditable(false);
        txtX2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnEquac.setText("Calcular Equação");
        btnEquac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquacActionPerformed(evt);
            }
        });

        btnZerarEq.setText("Zerar");
        btnZerarEq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZerarEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZerarEqActionPerformed(evt);
            }
        });

        lblDeltaMenor.setForeground(new java.awt.Color(255, 51, 0));
        lblDeltaMenor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeltaMenor.setText("...");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Informe os Valores");

        lblPasso1.setForeground(new java.awt.Color(255, 51, 0));
        lblPasso1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasso1.setText("...");

        lblPasso2.setForeground(new java.awt.Color(255, 51, 0));
        lblPasso2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasso2.setText("...");

        lblPasso4.setForeground(new java.awt.Color(255, 51, 0));
        lblPasso4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPasso4.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDeltaMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPasso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPasso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPasso4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZerarEq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblX1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(lblX2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEquac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtB, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblB)
                                .addComponent(lblC))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblX1)
                    .addComponent(lblX2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEquac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnZerarEq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDeltaMenor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasso2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasso4)
                .addGap(10, 10, 10))
        );

        jPanel2.setBackground(new java.awt.Color(102, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(58, 54));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EQUAÇÃO 2º GRAU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEquacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquacActionPerformed
        // Botão que calcula a equação do segundo grau.
        DecimalFormat df = new DecimalFormat("0.#");
        DecimalFormat outro = new DecimalFormat("0.##");
        double a,b,c,x1,x2,b2, delta,raiz;
        a = Double.parseDouble(txtA.getText());
        b = Double.parseDouble(txtB.getText());
        c = Double.parseDouble(txtC.getText());
        lblDeltaMenor.setText("A Equação é:");
        lblPasso1.setText(outro.format(a)+"x² + "+outro.format(b)+" x + "+outro.format(c));
        if (a != 0)
        {
            delta = (b*b)-(4)*(a)*(c);
            raiz = Math.sqrt(delta);

            if (delta == 0)
            {
                x1 = (-b + raiz)/(2*a);
                lblPasso2.setText("A valor de delta é: "+ outro.format(delta));
                lblPasso4.setText("A raiz de delta é: "+ outro.format(raiz));
                txtX1.setText(""+df.format(x1));
                txtX2.setText(""+df.format(x1));
            }
            else if (delta > 0)
            {
                x1 = (-b + raiz)/(2*a);
                x2 = (-b - raiz)/(2*a);
                lblPasso2.setText("A valor de delta é: "+ outro.format(delta));
                lblPasso4.setText("A raiz de delta é: "+ outro.format(raiz));
                txtX1.setText(""+df.format(x1));
                txtX2.setText(""+df.format(x2));
            }
            else if (delta < 0)
            {
                lblPasso1.setText("A valor de delta é: "+ outro.format(delta));                                                
                delta = -1*delta;
                raiz = Math.sqrt(delta);
                if ((-b) % (2*a) != 0)
                {                    
                    txtX1.setText(df.format(-b)+"+"+outro.format(raiz)+"i"+"/"+outro.format(2*a));
                    txtX2.setText(df.format(-b)+"-"+outro.format(raiz)+"i"+"/"+outro.format(2*a));
                    lblPasso2.setText("x' = "+(df.format(-b)+"+"+outro.format(raiz)+"i"+"/"+outro.format(2*a)));
                    lblPasso4.setText("x' = "+(df.format(-b)+"-"+outro.format(raiz)+"i"+"/"+outro.format(2*a)));
                    lblDeltaMenor.setText("Não existem raízes reais");
                }
                else
                {
                    double valor;
                    valor = raiz/(2*a);
                    if (valor == 1)
                    {                                             
                        txtX1.setText(df.format((-b)/(2*a))+"+"+"i");
                        txtX2.setText(df.format((-b)/(2*a))+"-"+"i");
                        lblPasso2.setText("x' = "+(df.format((-b)/(2*a))+"+"+"i"));
                        lblPasso4.setText("x' = "+(df.format((-b)/(2*a))+"-"+"i"));
                        lblDeltaMenor.setText("Não existem raízes reais");
                    }
                }
            }
    }//GEN-LAST:event_btnEquacActionPerformed
}
    private void btnZerarEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZerarEqActionPerformed
        // TODO add your handling code here:
        txtA.setText("");
        txtB.setText("");
        txtC.setText("");
        txtX1.setText("");
        txtX2.setText("");
        lblPasso1.setText("...");
        lblPasso2.setText("...");
        lblPasso4.setText("...");
        lblDeltaMenor.setText("...");
    }//GEN-LAST:event_btnZerarEqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquac;
    private javax.swing.JButton btnZerarEq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblDeltaMenor;
    private javax.swing.JLabel lblPasso1;
    private javax.swing.JLabel lblPasso2;
    private javax.swing.JLabel lblPasso4;
    private javax.swing.JLabel lblX1;
    private javax.swing.JLabel lblX2;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    // End of variables declaration//GEN-END:variables
}
